name: Build and Release

on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build
        run: |
          pnpm install
          pnpm run build

  create-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      
      - name: Generate changelog
        id: create_release
        run: npx changelogithub --name ${{ steps.vars.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: patch version
        run: |
          node ./scripts/patchVersion.js --version ${{ steps.vars.outputs.tag }}

      - name: publish npm
        run: cd dist && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
